<a href="https://colab.research.google.com/github/jaimeisaac2020/Metodos-Numericos/blob/mi-github/inversa_y_producto_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [3]:
A=np.array([[-3649,370],[21690,-3649]])
print(A)

[[-3649   370]
 [21690 -3649]]


In [4]:
A_inv=np.linalg.inv(A)

In [5]:
A_inv

array([[-6.89804970e-04, -6.99445982e-05],
       [-4.10026577e-03, -6.89804970e-04]])

In [6]:
B=np.array([[-4743],[37200]])

In [8]:
A_inv.dot(B)

array([[ 0.66980592],
       [-6.21318433]])