<a href="https://colab.research.google.com/github/jaimeisaac2020/Metodos-Numericos/blob/mi-github/polinomios_complejas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [58]:
import numpy as np

In [59]:
p=[3,-2,4,-3,1,-2,0,5]

In [60]:
np.roots(p)

array([ 0.96097538+0.40865895j,  0.96097538-0.40865895j,
        0.26561221+1.23340254j,  0.26561221-1.23340254j,
       -0.50200482+0.98742683j, -0.50200482-0.98742683j,
       -0.78249887+0.j        ])

In [61]:
import numpy as np

In [62]:
p=[1,0,2,0,4]

In [63]:
np.roots(p)

array([-0.70710678+1.22474487j, -0.70710678-1.22474487j,
        0.70710678+1.22474487j,  0.70710678-1.22474487j])

In [64]:
from scipy.optimize import fsolve

In [66]:
f= lambda x: 3*(x**7)-2*(x**6)+4*(x**5)-3*(x**4)+x**3-2*(x**2)+5

In [67]:
import numpy as np

In [68]:
x=np.arange(-10,11,1)

In [69]:
x

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10])

In [70]:
f(x)

array([-32431195, -15668554,  -6959739,  -2780794,   -968395,   -280170,
          -62299,     -9274,      -699,       -10,         5,         6,
             341,      5846,     44325,    213830,    773861,   2295606,
         5886341,  13503110,  28370805])

In [71]:
import pandas as pd
tabla=pd.DataFrame(f(x),a)
tabla

0
-10 -32431195
-9  -15668554
-8   -6959739
-7   -2780794
-6    -968395
-5    -280170
-4     -62299
-3      -9274
-2       -699
-1        -10
 0          5
 1          6
 2        341
 3       5846
 4      44325
 5     213830
 6     773861
 7    2295606
 8    5886341
 9   13503110
 10  28370805

In [73]:
f(x)

array([-32431195, -15668554,  -6959739,  -2780794,   -968395,   -280170,
          -62299,     -9274,      -699,       -10,         5,         6,
             341,      5846,     44325,    213830,    773861,   2295606,
         5886341,  13503110,  28370805])

In [75]:
fsolve(f,[-2])

array([-0.78249887])

In [76]:
# Método de Newton-Raphson
# Ejemplo 1 (Burden ejemplo 1 p.51/pdf.61)

import numpy as np

# INGRESO
fx  = lambda x: 3*x**7 - 2*(x**6) +4*(x**5)-3*(x**4)+x**3-2*(x**2)+5
dfx = lambda x: 21*x**6 - 12*(x**5) +20*(x**4)-12*(x**3)+3*x**2-4*(x)

x0 = -1
tolera = 0.00001

# PROCEDIMIENTO
tabla = []
tramo = abs(2*tolera)
xi = x0
while (tramo>=tolera):
    xnuevo = xi - fx(xi)/dfx(xi)
    tramo  = abs(xnuevo-xi)
    tabla.append([xi,xnuevo,tramo])
    xi = xnuevo

# convierte la lista a un arreglo.
tabla = np.array(tabla)
n = len(tabla)

# SALIDA
print(['xi', 'xnuevo', 'tramo'])
np.set_printoptions(precision = 4)
print(tabla)
print('raiz en: ', xi)
print('con error de: ',tramo)

['xi', 'xnuevo', 'tramo']
[[-1.0000e+00 -8.6111e-01  1.3889e-01]
 [-8.6111e-01 -7.9542e-01  6.5687e-02]
 [-7.9542e-01 -7.8289e-01  1.2531e-02]
 [-7.8289e-01 -7.8250e-01  3.9401e-04]
 [-7.8250e-01 -7.8250e-01  3.7611e-07]]
raiz en:  -0.7824988692822693
con error de:  3.7611216829880334e-07


In [ ]:
p=np.poly1d([3,-2,4,-3,1,-2,0,5])
q=np.poly1d([1,0.7824988692822693])

In [ ]:
p/q

(poly1d([ 3.    , -4.3475,  7.4019, -8.792 ,  7.8797, -8.1659,  6.3898]),
 poly1d([-9.0914e-12]))